[package]
name = "macos_keyboard_for_window"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rdev = { git = "https://github.com/Narsil/rdev/", features=["unstable_grab", "serialize"] }
serde = "1.0.160"
serde_cbor = "0.11.1"
serde_json = "1.0.96"
